# Install pre-commit hooks via
# pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c # frozen: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ffb6a759a979008c0e6dff86e39f4745a2d9eac4 # frozen: v3.1.0
    hooks:
      - id: prettier
        files: \.(md|rst|yml|yaml)
        args: [--prose-wrap=preserve]

  - repo: https://github.com/psf/black
    rev: 552baf822992936134cbd31a38f69c8cfe7c0f05 # frozen: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 960ead214cd1184149d366c6d27ca6c369ce46b6 # frozen: 1.16.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: 582556b052c898dc484a981bea48de3284a4b8ee # frozen: v0.16.0
    hooks:
      - id: cython-lint
        args: [--no-pycodestyle, --max-line-length=88]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c0bff48397a5119af3fadb07c507dd09ac9e2aa8 # frozen: v0.3.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/codespell-project/codespell
    rev: "6e41aba91fb32e9feb741a6258eefeb9c6e4a482" # frozen: v2.2.6
    hooks:
      - id: codespell
        args: ["-w", "-L", "ans,nd,sav,mke,ags,mot,coo,whos,manuel"]
