[tool.isort]
known_spcore = "numpy, scipy"
known_mpl = "matplotlib, mpl_toolkits"
known_pydatas = "pandas, seabborn, skimage, sklearn, statsmodels, sympy"
sections = "FUTURE,STDLIB,THIRDPARTY,SPCORE,MPL,FIRSTPARTY,PYDATAS,LOCALFOLDER"
no_lines_before= "MPL,FIRSTPARTY,PYDATAS"
force_sort_within_sections = true
