[tool.isort]
known_pydata = "numpy, scipy, pandas, matplotlib.pyplot, seabborn, skimage, sklearn, statsmodels, sympy"
known_firstparty = "matplotlib,mpl_toolkits"
sections = "FUTURE,STDLIB,THIRDPARTY,PYDATA,FIRSTPARTY,LOCALFOLDER"
force_sort_within_sections = true
