version: 2.1

jobs:
  build:
    docker:
      - image: danteev/texlive

    steps:
      - checkout

      - restore_cache:
          keys:
            - pip-cache-v1

      - run:
          name: Install Python dependencies
          command: |
            pip install -U pip
            pip install -r requirements.txt
            pip list

      - save_cache:
          key: pip-cache-v1
          paths:
            - ~/.cache/pip

      - run:
          name: Build docs
          command: |
            # NOTE: bad interaction w/ blas multithreading on circleci
            export OMP_NUM_THREADS=1
            make html  # FIX: check that failing examples produce failure

      - store_artifacts:
          path: build/html
